[metadata]
name = hir
version = 0.1.0
description = Herramienta para Ingenieros en Redes (CLI)
author = Tu Nombre
license = MIT

[options]
package_dir =
    = src
packages = find:
include_package_data = True
python_requires = >=3.10
install_requires =
    Jinja2
    prompt_toolkit
    python-nmap
    rich
    scapy

[options.packages.find]
where = src
include = hir, hir.*
exclude =
    tests*
    results*
    rust_ext*

[options.package_data]
hir.output = templates/*.j2

[options.entry_points]
console_scripts =
    hir = hir.cli:main
